# Form implementation generated from reading ui file 'beckyAug26.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 152)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:11pt  \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"}\n"
"QSpinBox {\n"
"padding-left:1.4em;\n"
"border:none;\n"
"background:transparent;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider:vertical {\n"
"min-width:40px;\n"
"min-height:75px;\n"
"max-height:75px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"border-radius: 7px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"background:rgb(22, 24, 29);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"background: rgba(233,123,111,0.25);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: rgb(233,123,111);\n"
"height: 14px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background:transparent;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background-color: rgb(255,163,151);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"background-color:rgb(188,78,66);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.mainStack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.mainStack.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:9px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.mainStack.setObjectName("mainStack")
        self.stackGrid = QtWidgets.QWidget()
        self.stackGrid.setObjectName("stackGrid")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stackGrid)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.stackGrid)
        self.stackedWidget.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(100,199,211);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(100,199,211);\n"
"    }\n"
"    \n"
"QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"min-width:15px;\n"
"max-width:20px;\n"
"margin-left:9px;\n"
"padding:5px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: white;\n"
"font-weight:bold;\n"
"color:black;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageOne = QtWidgets.QWidget()
        self.pageOne.setObjectName("pageOne")
        self.gridLayout = QtWidgets.QGridLayout(self.pageOne)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.pageOne)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b_slider = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_slider.sizePolicy().hasHeightForWidth())
        self.b_slider.setSizePolicy(sizePolicy)
        self.b_slider.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(100,150,178);}\n"
"QSlider::handle:vertical:hover {background:rgb(140,190,218);}\n"
"QSlider::handle:vertical:pressed {background:rgb(50,100,128);}\n"
"QSlider::groove:vertical:hover {background:rgba(100,150,178,0.25);}\n"
"QSlider::groove:vertical {background:rgba(100,150,178,0.15);}\n"
"\n"
"        ")
        self.b_slider.setMaximum(3)
        self.b_slider.setProperty("value", 0)
        self.b_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider.setInvertedAppearance(True)
        self.b_slider.setObjectName("b_slider")
        self.gridLayout_2.addWidget(self.b_slider, 1, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout_2.addWidget(self.frame1, 1, 1, 1, 1)
        self.b_box = QtWidgets.QSpinBox(parent=self.frame)
        self.b_box.setFrame(False)
        self.b_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box.setObjectName("b_box")
        self.gridLayout_2.addWidget(self.b_box, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne)
        self.pageOne1 = QtWidgets.QWidget()
        self.pageOne1.setObjectName("pageOne1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pageOne1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(parent=self.pageOne1)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_28.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.b_slider_2 = QtWidgets.QSlider(parent=self.frame_13)
        self.b_slider_2.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(67,149,223);}\n"
"QSlider::handle:vertical:hover {background:rgb(107,189,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(17,99,173);}\n"
"QSlider::groove:vertical:hover {background:rgba(67,149,223,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(67,149,223,0.15);}\n"
"\n"
"        ")
        self.b_slider_2.setMaximum(3)
        self.b_slider_2.setProperty("value", 0)
        self.b_slider_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_2.setInvertedAppearance(True)
        self.b_slider_2.setObjectName("b_slider_2")
        self.gridLayout_28.addWidget(self.b_slider_2, 1, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(parent=self.frame2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(parent=self.frame2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(parent=self.frame2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.frame2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.gridLayout_28.addWidget(self.frame2, 1, 1, 1, 1)
        self.b_box_2 = QtWidgets.QSpinBox(parent=self.frame_13)
        self.b_box_2.setFrame(False)
        self.b_box_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_2.setObjectName("b_box_2")
        self.gridLayout_28.addWidget(self.b_box_2, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_13, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne1)
        self.pageOne2 = QtWidgets.QWidget()
        self.pageOne2.setObjectName("pageOne2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageOne2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 2, 0, 1, 1)
        self.frame3 = QtWidgets.QFrame(parent=self.pageOne2)
        self.frame3.setObjectName("frame3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame3)
        self.gridLayout_29.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.b_slider_3 = QtWidgets.QSlider(parent=self.frame3)
        self.b_slider_3.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(82,145,226);}\n"
"QSlider::handle:vertical:hover {background:rgb(122,185,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(32,95,176);}\n"
"QSlider::groove:vertical:hover {background:rgba(82,145,226,0.25);}\n"
"QSlider::groove:vertical {background:rgba(82,145,226,0.15);}\n"
"\n"
"        ")
        self.b_slider_3.setMaximum(3)
        self.b_slider_3.setProperty("value", 0)
        self.b_slider_3.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_3.setInvertedAppearance(True)
        self.b_slider_3.setObjectName("b_slider_3")
        self.gridLayout_29.addWidget(self.b_slider_3, 1, 0, 1, 1)
        self.frame4 = QtWidgets.QFrame(parent=self.frame3)
        self.frame4.setObjectName("frame4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame4)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.frame4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.frame4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.frame4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.gridLayout_29.addWidget(self.frame4, 1, 1, 1, 1)
        self.b_box_3 = QtWidgets.QSpinBox(parent=self.frame3)
        self.b_box_3.setFrame(False)
        self.b_box_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_3.setObjectName("b_box_3")
        self.gridLayout_29.addWidget(self.b_box_3, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame3, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne2)
        self.pageOne3 = QtWidgets.QWidget()
        self.pageOne3.setObjectName("pageOne3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageOne3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.pageOne3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_30.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.b_slider_4 = QtWidgets.QSlider(parent=self.frame_2)
        self.b_slider_4.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(97,141,228);}\n"
"QSlider::handle:vertical:hover {background:rgb(137,181,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(47,91,178);}\n"
"QSlider::groove:vertical:hover {background:rgba(97,141,228,0.25);}\n"
"QSlider::groove:vertical {background:rgba(97,141,228,0.15);}\n"
"\n"
"        ")
        self.b_slider_4.setMaximum(3)
        self.b_slider_4.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_4.setInvertedAppearance(True)
        self.b_slider_4.setInvertedControls(False)
        self.b_slider_4.setObjectName("b_slider_4")
        self.gridLayout_30.addWidget(self.b_slider_4, 1, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.gridLayout_30.addWidget(self.frame_20, 1, 1, 1, 1)
        self.b_box_4 = QtWidgets.QSpinBox(parent=self.frame_2)
        self.b_box_4.setFrame(False)
        self.b_box_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_4.setObjectName("b_box_4")
        self.gridLayout_30.addWidget(self.b_box_4, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.frame_2, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne3)
        self.pageOne4 = QtWidgets.QWidget()
        self.pageOne4.setObjectName("pageOne4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pageOne4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 3, 0, 1, 1)
        self.frame5 = QtWidgets.QFrame(parent=self.pageOne4)
        self.frame5.setObjectName("frame5")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame5)
        self.gridLayout_31.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.b_slider_5 = QtWidgets.QSlider(parent=self.frame5)
        self.b_slider_5.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(113,136,229);}\n"
"QSlider::handle:vertical:hover {background:rgb(153,176,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(63,86,179);}\n"
"QSlider::groove:vertical:hover {background:rgba(113,136,229,0.25);}\n"
"QSlider::groove:vertical {background:rgba(113,136,229,0.15);}\n"
"")
        self.b_slider_5.setMaximum(3)
        self.b_slider_5.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_5.setInvertedAppearance(True)
        self.b_slider_5.setObjectName("b_slider_5")
        self.gridLayout_31.addWidget(self.b_slider_5, 1, 0, 1, 1)
        self.frame6 = QtWidgets.QFrame(parent=self.frame5)
        self.frame6.setObjectName("frame6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_30 = QtWidgets.QLabel(parent=self.frame6)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_8.addWidget(self.label_30)
        self.label_33 = QtWidgets.QLabel(parent=self.frame6)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_8.addWidget(self.label_33)
        self.label_32 = QtWidgets.QLabel(parent=self.frame6)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_8.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(parent=self.frame6)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.gridLayout_31.addWidget(self.frame6, 1, 1, 1, 1)
        self.b_box_5 = QtWidgets.QSpinBox(parent=self.frame5)
        self.b_box_5.setFrame(False)
        self.b_box_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_5.setObjectName("b_box_5")
        self.gridLayout_31.addWidget(self.b_box_5, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame5, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne4)
        self.pageOne5 = QtWidgets.QWidget()
        self.pageOne5.setObjectName("pageOne5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageOne5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem11, 3, 0, 1, 1)
        self.frame7 = QtWidgets.QFrame(parent=self.pageOne5)
        self.frame7.setObjectName("frame7")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame7)
        self.gridLayout_32.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.frame8 = QtWidgets.QFrame(parent=self.frame7)
        self.frame8.setObjectName("frame8")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame8)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_82 = QtWidgets.QLabel(parent=self.frame8)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_21.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(parent=self.frame8)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_21.addWidget(self.label_83)
        self.label_84 = QtWidgets.QLabel(parent=self.frame8)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_21.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(parent=self.frame8)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_21.addWidget(self.label_85)
        self.gridLayout_32.addWidget(self.frame8, 1, 1, 1, 1)
        self.b_slider_6 = QtWidgets.QSlider(parent=self.frame7)
        self.b_slider_6.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(128,131,228);}\n"
"QSlider::handle:vertical:hover {background:rgb(168,171,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(78,81,178);}\n"
"QSlider::groove:vertical:hover {background:rgba(128,131,228,0.25);}\n"
"QSlider::groove:vertical {background:rgba(128,131,228,0.15);}\n"
"        ")
        self.b_slider_6.setMaximum(3)
        self.b_slider_6.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_6.setInvertedAppearance(True)
        self.b_slider_6.setObjectName("b_slider_6")
        self.gridLayout_32.addWidget(self.b_slider_6, 1, 0, 1, 1)
        self.b_box_6 = QtWidgets.QSpinBox(parent=self.frame7)
        self.b_box_6.setFrame(False)
        self.b_box_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_6.setObjectName("b_box_6")
        self.gridLayout_32.addWidget(self.b_box_6, 0, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame7, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne5)
        self.pageOne6 = QtWidgets.QWidget()
        self.pageOne6.setObjectName("pageOne6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pageOne6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem12, 2, 0, 1, 1)
        self.frame9 = QtWidgets.QFrame(parent=self.pageOne6)
        self.frame9.setObjectName("frame9")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame9)
        self.gridLayout_33.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.b_slider_7 = QtWidgets.QSlider(parent=self.frame9)
        self.b_slider_7.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(142,125,225);}\n"
"QSlider::handle:vertical:hover {background:rgb(182,165,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(92,75,175);}\n"
"QSlider::groove:vertical:hover {background:rgba(142,125,225,0.25);}\n"
"QSlider::groove:vertical {background:rgba(142,125,225,0.15);}\n"
"\n"
"        ")
        self.b_slider_7.setMaximum(3)
        self.b_slider_7.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_7.setInvertedAppearance(True)
        self.b_slider_7.setObjectName("b_slider_7")
        self.gridLayout_33.addWidget(self.b_slider_7, 1, 0, 1, 1)
        self.frame10 = QtWidgets.QFrame(parent=self.frame9)
        self.frame10.setObjectName("frame10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_34 = QtWidgets.QLabel(parent=self.frame10)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_9.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(parent=self.frame10)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_9.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(parent=self.frame10)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_9.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(parent=self.frame10)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.gridLayout_33.addWidget(self.frame10, 1, 1, 1, 1)
        self.b_box_7 = QtWidgets.QSpinBox(parent=self.frame9)
        self.b_box_7.setFrame(False)
        self.b_box_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_7.setObjectName("b_box_7")
        self.gridLayout_33.addWidget(self.b_box_7, 0, 0, 1, 2)
        self.gridLayout_10.addWidget(self.frame9, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne6)
        self.pageOne7 = QtWidgets.QWidget()
        self.pageOne7.setObjectName("pageOne7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pageOne7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame11 = QtWidgets.QFrame(parent=self.pageOne7)
        self.frame11.setObjectName("frame11")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.frame11)
        self.gridLayout_34.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.frame12 = QtWidgets.QFrame(parent=self.frame11)
        self.frame12.setObjectName("frame12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_26 = QtWidgets.QLabel(parent=self.frame12)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(parent=self.frame12)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_7.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.frame12)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(parent=self.frame12)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.gridLayout_34.addWidget(self.frame12, 1, 1, 1, 1)
        self.b_slider_8 = QtWidgets.QSlider(parent=self.frame11)
        self.b_slider_8.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(156,119,221);}\n"
"QSlider::handle:vertical:hover {background:rgb(196,159,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(106,69,171);}\n"
"QSlider::groove:vertical:hover {background:rgba(156,119,221,0.25);}\n"
"QSlider::groove:vertical {background:rgba(156,119,221,0.15);}\n"
"\n"
"        ")
        self.b_slider_8.setMaximum(3)
        self.b_slider_8.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_8.setInvertedAppearance(True)
        self.b_slider_8.setObjectName("b_slider_8")
        self.gridLayout_34.addWidget(self.b_slider_8, 1, 0, 1, 1)
        self.b_box_8 = QtWidgets.QSpinBox(parent=self.frame11)
        self.b_box_8.setFrame(False)
        self.b_box_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_8.setObjectName("b_box_8")
        self.gridLayout_34.addWidget(self.b_box_8, 0, 0, 1, 2)
        self.gridLayout_11.addWidget(self.frame11, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_11.addItem(spacerItem14, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_11.addItem(spacerItem15, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne7)
        self.pageOne8 = QtWidgets.QWidget()
        self.pageOne8.setObjectName("pageOne8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pageOne8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_12.addItem(spacerItem16, 2, 0, 1, 1)
        self.frame13 = QtWidgets.QFrame(parent=self.pageOne8)
        self.frame13.setObjectName("frame13")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame13)
        self.gridLayout_35.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.b_slider_9 = QtWidgets.QSlider(parent=self.frame13)
        self.b_slider_9.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(170,112,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(210,152,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(120,62,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(170,112,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(170,112,215,0.15);}\n"
"\n"
"        ")
        self.b_slider_9.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_9.setInvertedAppearance(True)
        self.b_slider_9.setObjectName("b_slider_9")
        self.gridLayout_35.addWidget(self.b_slider_9, 1, 0, 1, 1)
        self.frame14 = QtWidgets.QFrame(parent=self.frame13)
        self.frame14.setObjectName("frame14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame14)
        self.verticalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(parent=self.frame14)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.frame14)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.frame14)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(parent=self.frame14)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.gridLayout_35.addWidget(self.frame14, 1, 1, 1, 1)
        self.b_box_9 = QtWidgets.QSpinBox(parent=self.frame13)
        self.b_box_9.setFrame(False)
        self.b_box_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_9.setObjectName("b_box_9")
        self.gridLayout_35.addWidget(self.b_box_9, 0, 0, 1, 2)
        self.gridLayout_12.addWidget(self.frame13, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_12.addItem(spacerItem17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne8)
        self.pageOne9 = QtWidgets.QWidget()
        self.pageOne9.setObjectName("pageOne9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.pageOne9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_13.addItem(spacerItem18, 2, 0, 1, 1)
        self.frame15 = QtWidgets.QFrame(parent=self.pageOne9)
        self.frame15.setObjectName("frame15")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.frame15)
        self.gridLayout_36.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.b_slider_10 = QtWidgets.QSlider(parent=self.frame15)
        self.b_slider_10.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(183,104,208);}\n"
"QSlider::handle:vertical:hover {background:rgb(223,144,248);}\n"
"QSlider::handle:vertical:pressed {background:rgb(133,54,158);}\n"
"QSlider::groove:vertical:hover {background:rgba(183,104,208,0.25);}\n"
"QSlider::groove:vertical {background:rgba(183,104,208,0.15);}\n"
"\n"
"        ")
        self.b_slider_10.setMaximum(3)
        self.b_slider_10.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_10.setInvertedAppearance(True)
        self.b_slider_10.setInvertedControls(False)
        self.b_slider_10.setObjectName("b_slider_10")
        self.gridLayout_36.addWidget(self.b_slider_10, 1, 0, 1, 1)
        self.frame16 = QtWidgets.QFrame(parent=self.frame15)
        self.frame16.setObjectName("frame16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame16)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(parent=self.frame16)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(parent=self.frame16)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(parent=self.frame16)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.frame16)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.gridLayout_36.addWidget(self.frame16, 1, 1, 1, 1)
        self.b_box_10 = QtWidgets.QSpinBox(parent=self.frame15)
        self.b_box_10.setFrame(False)
        self.b_box_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_10.setObjectName("b_box_10")
        self.gridLayout_36.addWidget(self.b_box_10, 0, 0, 1, 2)
        self.gridLayout_13.addWidget(self.frame15, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_13.addItem(spacerItem19, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne9)
        self.pageOne10 = QtWidgets.QWidget()
        self.pageOne10.setObjectName("pageOne10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.pageOne10)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame17 = QtWidgets.QFrame(parent=self.pageOne10)
        self.frame17.setObjectName("frame17")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame17)
        self.gridLayout_37.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.frame18 = QtWidgets.QFrame(parent=self.frame17)
        self.frame18.setObjectName("frame18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame18)
        self.verticalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_38 = QtWidgets.QLabel(parent=self.frame18)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_10.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(parent=self.frame18)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_10.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(parent=self.frame18)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_10.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(parent=self.frame18)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.gridLayout_37.addWidget(self.frame18, 1, 1, 1, 1)
        self.b_slider_11 = QtWidgets.QSlider(parent=self.frame17)
        self.b_slider_11.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(194,96,199);}\n"
"QSlider::handle:vertical:hover {background:rgb(234,136,239);}\n"
"QSlider::handle:vertical:pressed {background:rgb(144,46,149);}\n"
"QSlider::groove:vertical:hover {background:rgba(194,96,199,0.25);}\n"
"QSlider::groove:vertical {background:rgba(194,96,199,0.15);}\n"
"\n"
"        ")
        self.b_slider_11.setMaximum(3)
        self.b_slider_11.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_11.setInvertedAppearance(True)
        self.b_slider_11.setObjectName("b_slider_11")
        self.gridLayout_37.addWidget(self.b_slider_11, 1, 0, 1, 1)
        self.b_box_11 = QtWidgets.QSpinBox(parent=self.frame17)
        self.b_box_11.setFrame(False)
        self.b_box_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_11.setObjectName("b_box_11")
        self.gridLayout_37.addWidget(self.b_box_11, 0, 0, 1, 2)
        self.gridLayout_15.addWidget(self.frame17, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_15.addItem(spacerItem20, 2, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_15.addItem(spacerItem21, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne10)
        self.pageOne11 = QtWidgets.QWidget()
        self.pageOne11.setObjectName("pageOne11")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.pageOne11)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_16.addItem(spacerItem22, 2, 0, 1, 1)
        self.frame19 = QtWidgets.QFrame(parent=self.pageOne11)
        self.frame19.setObjectName("frame19")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.frame19)
        self.gridLayout_38.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.b_slider_12 = QtWidgets.QSlider(parent=self.frame19)
        self.b_slider_12.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(205,88,188);}\n"
"QSlider::handle:vertical:hover {background:rgb(245,128,228);}\n"
"QSlider::handle:vertical:pressed {background:rgb(155,38,138);}\n"
"QSlider::groove:vertical:hover {background:rgba(205,88,188,0.25);}\n"
"QSlider::groove:vertical {background:rgba(205,88,188,0.15);}\n"
"\n"
"        ")
        self.b_slider_12.setMaximum(3)
        self.b_slider_12.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_12.setInvertedAppearance(True)
        self.b_slider_12.setObjectName("b_slider_12")
        self.gridLayout_38.addWidget(self.b_slider_12, 1, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(parent=self.frame19)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_42 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_11.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_11.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_11.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.gridLayout_38.addWidget(self.frame_21, 1, 1, 1, 1)
        self.b_box_12 = QtWidgets.QSpinBox(parent=self.frame19)
        self.b_box_12.setFrame(False)
        self.b_box_12.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_12.setObjectName("b_box_12")
        self.gridLayout_38.addWidget(self.b_box_12, 0, 0, 1, 2)
        self.gridLayout_16.addWidget(self.frame19, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_16.addItem(spacerItem23, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne11)
        self.pageOne12 = QtWidgets.QWidget()
        self.pageOne12.setObjectName("pageOne12")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.pageOne12)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_18.addItem(spacerItem24, 2, 0, 1, 1)
        self.frame20 = QtWidgets.QFrame(parent=self.pageOne12)
        self.frame20.setObjectName("frame20")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame20)
        self.gridLayout_39.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame20)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_46 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_12.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_12.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_12.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_12.addWidget(self.label_49)
        self.gridLayout_39.addWidget(self.frame_3, 1, 1, 1, 1)
        self.b_slider_13 = QtWidgets.QSlider(parent=self.frame20)
        self.b_slider_13.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(214,79,176);}\n"
"QSlider::handle:vertical:hover {background:rgb(254,119,216);}\n"
"QSlider::handle:vertical:pressed {background:rgb(164,29,126);}\n"
"QSlider::groove:vertical:hover {background:rgba(214,79,176,0.25);}\n"
"QSlider::groove:vertical {background:rgba(214,79,176,0.15);}\n"
"\n"
"        ")
        self.b_slider_13.setMaximum(3)
        self.b_slider_13.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_13.setInvertedAppearance(True)
        self.b_slider_13.setObjectName("b_slider_13")
        self.gridLayout_39.addWidget(self.b_slider_13, 1, 0, 1, 1)
        self.b_box_13 = QtWidgets.QSpinBox(parent=self.frame20)
        self.b_box_13.setFrame(False)
        self.b_box_13.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_13.setObjectName("b_box_13")
        self.gridLayout_39.addWidget(self.b_box_13, 0, 0, 1, 2)
        self.gridLayout_18.addWidget(self.frame20, 1, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_18.addItem(spacerItem25, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne12)
        self.pageOne13 = QtWidgets.QWidget()
        self.pageOne13.setObjectName("pageOne13")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.pageOne13)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_19.addItem(spacerItem26, 3, 0, 1, 1)
        self.frame21 = QtWidgets.QFrame(parent=self.pageOne13)
        self.frame21.setObjectName("frame21")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.frame21)
        self.gridLayout_40.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.b_slider_14 = QtWidgets.QSlider(parent=self.frame21)
        self.b_slider_14.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(99,160,201);}\n"
"QSlider::handle:vertical:hover {background:rgb(139,200,241);}\n"
"QSlider::handle:vertical:pressed {background:rgb(49,110,151);}\n"
"QSlider::groove:vertical:hover {background:rgba(99,160,201,0.25);}\n"
"QSlider::groove:vertical {background:rgba(99,160,201,0.15);}\n"
"\n"
"        ")
        self.b_slider_14.setMaximum(3)
        self.b_slider_14.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_14.setInvertedAppearance(True)
        self.b_slider_14.setObjectName("b_slider_14")
        self.gridLayout_40.addWidget(self.b_slider_14, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame21)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_50 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_13.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_13.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_13.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_13.addWidget(self.label_53)
        self.gridLayout_40.addWidget(self.frame_4, 1, 1, 1, 1)
        self.b_box_14 = QtWidgets.QSpinBox(parent=self.frame21)
        self.b_box_14.setFrame(False)
        self.b_box_14.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_14.setObjectName("b_box_14")
        self.gridLayout_40.addWidget(self.b_box_14, 0, 0, 1, 2)
        self.gridLayout_19.addWidget(self.frame21, 2, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_19.addItem(spacerItem27, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne13)
        self.pageOne14 = QtWidgets.QWidget()
        self.pageOne14.setObjectName("pageOne14")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.pageOne14)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_20.addItem(spacerItem28, 2, 0, 1, 1)
        self.frame22 = QtWidgets.QFrame(parent=self.pageOne14)
        self.frame22.setObjectName("frame22")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame22)
        self.gridLayout_41.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame22)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_54 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_14.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_14.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_14.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_14.addWidget(self.label_57)
        self.gridLayout_41.addWidget(self.frame_5, 1, 1, 1, 1)
        self.b_slider_15 = QtWidgets.QSlider(parent=self.frame22)
        self.b_slider_15.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(153,102,153);}\n"
"QSlider::handle:vertical:hover {background:rgb(193,142,193);}\n"
"QSlider::handle:vertical:pressed {background:rgb(103,52,103);}\n"
"QSlider::groove:vertical:hover {background:rgba(153,102,153,0.25);}\n"
"QSlider::groove:vertical {background:rgba(153,102,153,0.15);}\n"
"\n"
"        ")
        self.b_slider_15.setMaximum(3)
        self.b_slider_15.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_15.setInvertedAppearance(True)
        self.b_slider_15.setObjectName("b_slider_15")
        self.gridLayout_41.addWidget(self.b_slider_15, 1, 0, 1, 1)
        self.b_box_15 = QtWidgets.QSpinBox(parent=self.frame22)
        self.b_box_15.setFrame(False)
        self.b_box_15.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_15.setObjectName("b_box_15")
        self.gridLayout_41.addWidget(self.b_box_15, 0, 0, 1, 2)
        self.gridLayout_20.addWidget(self.frame22, 1, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_20.addItem(spacerItem29, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne14)
        self.pageOne15 = QtWidgets.QWidget()
        self.pageOne15.setObjectName("pageOne15")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pageOne15)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem30, 2, 0, 1, 1)
        self.frame23 = QtWidgets.QFrame(parent=self.pageOne15)
        self.frame23.setObjectName("frame23")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.frame23)
        self.gridLayout_42.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame23)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_58 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_15.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_15.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_15.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_15.addWidget(self.label_61)
        self.gridLayout_42.addWidget(self.frame_6, 1, 1, 1, 1)
        self.b_slider_16 = QtWidgets.QSlider(parent=self.frame23)
        self.b_slider_16.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(96,175,106);}\n"
"QSlider::handle:vertical:hover {background:rgb(136,215,146);}\n"
"QSlider::handle:vertical:pressed {background:rgb(46,125,56);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,175,106,0.25);}\n"
"QSlider::groove:vertical {background:rgba(96,175,106,0.15);}\n"
"\n"
"        ")
        self.b_slider_16.setMaximum(3)
        self.b_slider_16.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_16.setInvertedAppearance(True)
        self.b_slider_16.setObjectName("b_slider_16")
        self.gridLayout_42.addWidget(self.b_slider_16, 1, 0, 1, 1)
        self.b_box_16 = QtWidgets.QSpinBox(parent=self.frame23)
        self.b_box_16.setFrame(False)
        self.b_box_16.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_16.setObjectName("b_box_16")
        self.gridLayout_42.addWidget(self.b_box_16, 0, 0, 1, 2)
        self.gridLayout_9.addWidget(self.frame23, 1, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem31, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne15)
        self.pageOne16 = QtWidgets.QWidget()
        self.pageOne16.setObjectName("pageOne16")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.pageOne16)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.frame24 = QtWidgets.QFrame(parent=self.pageOne16)
        self.frame24.setObjectName("frame24")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.frame24)
        self.gridLayout_43.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.b_slider_17 = QtWidgets.QSlider(parent=self.frame24)
        self.b_slider_17.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(207,86,150);}\n"
"QSlider::handle:vertical:hover {background:rgb(247,126,190);}\n"
"QSlider::handle:vertical:pressed {background:rgb(157,36,100);}\n"
"QSlider::groove:vertical:hover {background:rgba(207,86,150,0.25);}\n"
"QSlider::groove:vertical {background:rgba(207,86,150,0.15);}\n"
"\n"
"        ")
        self.b_slider_17.setMaximum(3)
        self.b_slider_17.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_17.setInvertedAppearance(True)
        self.b_slider_17.setObjectName("b_slider_17")
        self.gridLayout_43.addWidget(self.b_slider_17, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame24)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_62 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_16.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_16.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_16.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_16.addWidget(self.label_65)
        self.gridLayout_43.addWidget(self.frame_7, 1, 1, 1, 1)
        self.b_box_17 = QtWidgets.QSpinBox(parent=self.frame24)
        self.b_box_17.setFrame(False)
        self.b_box_17.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_17.setObjectName("b_box_17")
        self.gridLayout_43.addWidget(self.b_box_17, 0, 0, 1, 2)
        self.gridLayout_22.addWidget(self.frame24, 1, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_22.addItem(spacerItem32, 2, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_22.addItem(spacerItem33, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne16)
        self.pageOne17 = QtWidgets.QWidget()
        self.pageOne17.setObjectName("pageOne17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.pageOne17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame25 = QtWidgets.QFrame(parent=self.pageOne17)
        self.frame25.setObjectName("frame25")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.frame25)
        self.gridLayout_44.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.b_slider_18 = QtWidgets.QSlider(parent=self.frame25)
        self.b_slider_18.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(236,46,103);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,86,143);}\n"
"QSlider::handle:vertical:pressed {background:rgb(186,0,53);}\n"
"QSlider::groove:vertical:hover {background:rgba(236,46,103,0.25);}\n"
"QSlider::groove:vertical {background:rgba(236,46,103,0.15);}\n"
"\n"
"        ")
        self.b_slider_18.setMaximum(3)
        self.b_slider_18.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_18.setInvertedAppearance(True)
        self.b_slider_18.setObjectName("b_slider_18")
        self.gridLayout_44.addWidget(self.b_slider_18, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame25)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_66 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_17.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_17.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_17.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_17.addWidget(self.label_69)
        self.gridLayout_44.addWidget(self.frame_8, 1, 1, 1, 1)
        self.b_box_18 = QtWidgets.QSpinBox(parent=self.frame25)
        self.b_box_18.setFrame(False)
        self.b_box_18.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_18.setObjectName("b_box_18")
        self.gridLayout_44.addWidget(self.b_box_18, 0, 0, 1, 2)
        self.gridLayout_23.addWidget(self.frame25, 1, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_23.addItem(spacerItem34, 2, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_23.addItem(spacerItem35, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne17)
        self.pageOne18 = QtWidgets.QWidget()
        self.pageOne18.setObjectName("pageOne18")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.pageOne18)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame26 = QtWidgets.QFrame(parent=self.pageOne18)
        self.frame26.setObjectName("frame26")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.frame26)
        self.gridLayout_45.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.b_slider_19 = QtWidgets.QSlider(parent=self.frame26)
        self.b_slider_19.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(236,47,87);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,87,127);}\n"
"QSlider::handle:vertical:pressed {background:rgb(186,0,37);}\n"
"QSlider::groove:vertical:hover {background:rgba(236,47,87,0.25);}\n"
"QSlider::groove:vertical {background:rgba(236,47,87,0.15);}\n"
"\n"
"        ")
        self.b_slider_19.setMaximum(3)
        self.b_slider_19.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_19.setInvertedAppearance(True)
        self.b_slider_19.setObjectName("b_slider_19")
        self.gridLayout_45.addWidget(self.b_slider_19, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame26)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_70 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_18.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_18.addWidget(self.label_71)
        self.label_72 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_18.addWidget(self.label_72)
        self.label_73 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_18.addWidget(self.label_73)
        self.gridLayout_45.addWidget(self.frame_9, 1, 1, 1, 1)
        self.b_box_19 = QtWidgets.QSpinBox(parent=self.frame26)
        self.b_box_19.setFrame(False)
        self.b_box_19.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_19.setObjectName("b_box_19")
        self.gridLayout_45.addWidget(self.b_box_19, 0, 0, 1, 2)
        self.gridLayout_24.addWidget(self.frame26, 1, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_24.addItem(spacerItem36, 2, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_24.addItem(spacerItem37, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne18)
        self.pageOne19 = QtWidgets.QWidget()
        self.pageOne19.setObjectName("pageOne19")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pageOne19)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame27 = QtWidgets.QFrame(parent=self.pageOne19)
        self.frame27.setObjectName("frame27")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.frame27)
        self.gridLayout_46.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.b_slider_20 = QtWidgets.QSlider(parent=self.frame27)
        self.b_slider_20.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(242,89,85);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,129,125);}\n"
"QSlider::handle:vertical:pressed {background:rgb(192,39,35);}\n"
"QSlider::groove:vertical:hover {background:rgba(242,89,85,0.25);}\n"
"QSlider::groove:vertical {background:rgba(242,89,85,0.15);}\n"
"\n"
"        ")
        self.b_slider_20.setMaximum(3)
        self.b_slider_20.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_20.setInvertedAppearance(True)
        self.b_slider_20.setObjectName("b_slider_20")
        self.gridLayout_46.addWidget(self.b_slider_20, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame27)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_74 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_74.setWordWrap(True)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_19.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_75.setWordWrap(True)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_19.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_76.setWordWrap(True)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_19.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_77.setWordWrap(True)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_19.addWidget(self.label_77)
        self.gridLayout_46.addWidget(self.frame_10, 1, 1, 1, 1)
        self.b_box_20 = QtWidgets.QSpinBox(parent=self.frame27)
        self.b_box_20.setFrame(False)
        self.b_box_20.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_20.setObjectName("b_box_20")
        self.gridLayout_46.addWidget(self.b_box_20, 0, 0, 1, 2)
        self.gridLayout_14.addWidget(self.frame27, 1, 0, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_14.addItem(spacerItem38, 2, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_14.addItem(spacerItem39, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne19)
        self.pageOne20 = QtWidgets.QWidget()
        self.pageOne20.setObjectName("pageOne20")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.pageOne20)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_12 = QtWidgets.QFrame(parent=self.pageOne20)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_47.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_78 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_20.addWidget(self.label_78)
        self.label_79 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_20.addWidget(self.label_79)
        self.label_80 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_80.setObjectName("label_80")
        self.verticalLayout_20.addWidget(self.label_80)
        self.label_81 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_20.addWidget(self.label_81)
        self.gridLayout_47.addWidget(self.frame_11, 1, 1, 1, 1)
        self.b_slider_21 = QtWidgets.QSlider(parent=self.frame_12)
        self.b_slider_21.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(189,97,218);}\n"
"QSlider::handle:vertical:hover {background:rgb(229,137,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(139,47,168);}\n"
"QSlider::groove:vertical:hover {background:rgba(189,97,218,0.25);}\n"
"QSlider::groove:vertical {background:rgba(189,97,218,0.15);}\n"
"\n"
"        ")
        self.b_slider_21.setMaximum(3)
        self.b_slider_21.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.b_slider_21.setInvertedAppearance(True)
        self.b_slider_21.setObjectName("b_slider_21")
        self.gridLayout_47.addWidget(self.b_slider_21, 1, 0, 1, 1)
        self.b_box_21 = QtWidgets.QSpinBox(parent=self.frame_12)
        self.b_box_21.setFrame(False)
        self.b_box_21.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.b_box_21.setObjectName("b_box_21")
        self.gridLayout_47.addWidget(self.b_box_21, 0, 0, 1, 2)
        self.gridLayout_17.addWidget(self.frame_12, 2, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_17.addItem(spacerItem40, 0, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_17.addItem(spacerItem41, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne20)
        self.pageOne21 = QtWidgets.QWidget()
        self.pageOne21.setObjectName("pageOne21")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.pageOne21)
        self.gridLayout_26.setObjectName("gridLayout_26")
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_26.addItem(spacerItem42, 2, 0, 1, 1)
        self.frame28 = QtWidgets.QFrame(parent=self.pageOne21)
        self.frame28.setObjectName("frame28")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.frame28)
        self.gridLayout_48.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame28)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 471, 144))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_25.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_48.addWidget(self.scrollArea, 1, 1, 1, 1)
        self.beck_summary = QtWidgets.QSlider(parent=self.frame28)
        self.beck_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(96,175,106);}\n"
"QSlider::handle:vertical:hover {background:rgb(136,215,146);}\n"
"QSlider::handle:vertical:pressed {background:rgb(46,125,56);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,175,106,0.25);}\n"
"QSlider::groove:vertical {background:rgba(96,175,106,0.15);}\n"
"\n"
"        ")
        self.beck_summary.setMaximum(64)
        self.beck_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.beck_summary.setInvertedAppearance(True)
        self.beck_summary.setObjectName("beck_summary")
        self.gridLayout_48.addWidget(self.beck_summary, 1, 0, 1, 1)
        self.sum_box = QtWidgets.QSpinBox(parent=self.frame28)
        self.sum_box.setFrame(False)
        self.sum_box.setReadOnly(True)
        self.sum_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.sum_box.setObjectName("sum_box")
        self.gridLayout_48.addWidget(self.sum_box, 0, 0, 1, 2)
        self.gridLayout_26.addWidget(self.frame28, 1, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_26.addItem(spacerItem43, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageOne21)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.mainStack.addWidget(self.stackGrid)
        self.pageTwo = QtWidgets.QWidget()
        self.pageTwo.setObjectName("pageTwo")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.pageTwo)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.hidemeframe = QtWidgets.QFrame(parent=self.pageTwo)
        self.hidemeframe.setObjectName("hidemeframe")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.hidemeframe)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.beck_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.beck_date.setObjectName("beck_date")
        self.verticalLayout_22.addWidget(self.beck_date)
        self.beck_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.beck_time.setObjectName("beck_time")
        self.verticalLayout_22.addWidget(self.beck_time)
        self.gridLayout_21.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.beck_table = QtWidgets.QTableView(parent=self.pageTwo)
        self.beck_table.setStyleSheet("\n"
" QTableView {\n"
"     background-color: transparent;\n"
"     selection-background-color: #7e57c2;\n"
"     gridline-color:transparent;\n"
"     color:rgb(46,58,146);\n"
" }\n"
" QTableView::item {\n"
"     padding: 1px;\n"
"     background:rgb(111,123,211);\n"
" }\n"
" QTableView::item:selected {\n"
"        color:rgb(46,58,146);\n"
"     background:rgb(23, 23, 23);\n"
" }\n"
" ")
        self.beck_table.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.beck_table.setShowGrid(False)
        self.beck_table.setSortingEnabled(True)
        self.beck_table.setObjectName("beck_table")
        self.beck_table.horizontalHeader().setCascadingSectionResizes(True)
        self.beck_table.horizontalHeader().setMinimumSectionSize(12)
        self.beck_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_21.addWidget(self.beck_table, 1, 0, 1, 1)
        self.mainStack.addWidget(self.pageTwo)
        self.gridLayout_27.addWidget(self.mainStack, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 16))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuData = QtWidgets.QMenu(parent=self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        MainWindow.setMenuBar(self.menubar)
        self.actionShowBeckExam = QtGui.QAction(parent=MainWindow)
        self.actionShowBeckExam.setObjectName("actionShowBeckExam")
        self.actionShowBeckTable = QtGui.QAction(parent=MainWindow)
        self.actionShowBeckTable.setObjectName("actionShowBeckTable")
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionNext = QtGui.QAction(parent=MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtGui.QAction(parent=MainWindow)
        self.actionPrev.setObjectName("actionPrev")
        self.actionHome = QtGui.QAction(parent=MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menuBECK.addAction(self.actionShowBeckExam)
        self.menuBECK.addAction(self.actionShowBeckTable)
        self.menuBECK.addAction(self.actionClose)
        self.menuData.addAction(self.actionCommit)
        self.menuData.addAction(self.actionDelete)
        self.menuViews.addAction(self.actionNext)
        self.menuViews.addAction(self.actionPrev)
        self.menuViews.addAction(self.actionHome)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Today, I do not feel sad."))
        self.label_3.setText(_translate("MainWindow", "Today, I feel sad."))
        self.label_4.setText(_translate("MainWindow", "Today, I feel sad all the time and can\'t snap out of it."))
        self.label_5.setText(_translate("MainWindow", "Today, I feel so sad and unhappy that I can\'t stand it."))
        self.label_11.setText(_translate("MainWindow", "I feel fine about the future"))
        self.label_10.setText(_translate("MainWindow", "I am not particularly discouraged about the future."))
        self.label_12.setText(_translate("MainWindow", "I feel I have nothing to look forward to."))
        self.label_13.setText(_translate("MainWindow", "I feel the future is hopeless and that things cannot improve."))
        self.label_6.setText(_translate("MainWindow", "I do not feel like a failure."))
        self.label_7.setText(_translate("MainWindow", "I feel I have failed more than the average person."))
        self.label_8.setText(_translate("MainWindow", "As I look back on my life, all I can see is a lot of failures."))
        self.label_9.setText(_translate("MainWindow", "I feel I am a complete failure as a person."))
        self.label_14.setText(_translate("MainWindow", "I get as much satisfaction out of things as I used to."))
        self.label_15.setText(_translate("MainWindow", "I don\'t enjoy things the way I used to."))
        self.label_16.setText(_translate("MainWindow", "I don\'t get real satisfaction out of anything anymore."))
        self.label_17.setText(_translate("MainWindow", "I am dissatisfied or bored with everything."))
        self.label_30.setText(_translate("MainWindow", "I don\'t feel particularly guilty"))
        self.label_33.setText(_translate("MainWindow", "I feel guilty a good part of the time."))
        self.label_32.setText(_translate("MainWindow", "I feel quite guilty most of the time."))
        self.label_31.setText(_translate("MainWindow", "I feel guilty all of the time."))
        self.label_82.setText(_translate("MainWindow", "I don\'t feel I am being punished."))
        self.label_83.setText(_translate("MainWindow", "I feel I may be punished."))
        self.label_84.setText(_translate("MainWindow", "I expect to be punished."))
        self.label_85.setText(_translate("MainWindow", "I feel I am being punished."))
        self.label_34.setText(_translate("MainWindow", "I don\'t feel disappointed in myself."))
        self.label_35.setText(_translate("MainWindow", "I am disappointed in myself."))
        self.label_36.setText(_translate("MainWindow", "I am disgusted with myself."))
        self.label_37.setText(_translate("MainWindow", "I hate myself."))
        self.label_26.setText(_translate("MainWindow", "I don\'t feel I am any worse than anybody else."))
        self.label_27.setText(_translate("MainWindow", "I am critical of myself for my weaknesses or mistakes."))
        self.label_28.setText(_translate("MainWindow", "I blame myself all the time for my faults."))
        self.label_29.setText(_translate("MainWindow", "I blame myself for everything bad that happens."))
        self.label_22.setText(_translate("MainWindow", "I don\'t have any thoughts of killing myself."))
        self.label_23.setText(_translate("MainWindow", "I have thoughts of killing myself, but I would not carry them out."))
        self.label_24.setText(_translate("MainWindow", "I would like to kill myself."))
        self.label_25.setText(_translate("MainWindow", "I would kill myself if I had the chance."))
        self.label_19.setText(_translate("MainWindow", "I don\'t cry any more than usual."))
        self.label_18.setText(_translate("MainWindow", "I cry more now than I used to."))
        self.label_20.setText(_translate("MainWindow", "I cry all the time now."))
        self.label_21.setText(_translate("MainWindow", "I used to be able to cry, but now I can\'t cry even though I want to."))
        self.label_38.setText(_translate("MainWindow", "I\'m not more irritable today than most days."))
        self.label_39.setText(_translate("MainWindow", "I am slightly more irritated now than usual."))
        self.label_40.setText(_translate("MainWindow", "I am quite annoyed or irritated a good deal of the time."))
        self.label_41.setText(_translate("MainWindow", "I feel irritated all the time."))
        self.label_42.setText(_translate("MainWindow", "Today I am as interested in others as I usually am."))
        self.label_43.setText(_translate("MainWindow", "I am less interested in other people than I used to be."))
        self.label_44.setText(_translate("MainWindow", "I have lost most of my interest in other people."))
        self.label_45.setText(_translate("MainWindow", "I have lost all of my interest in other people."))
        self.label_46.setText(_translate("MainWindow", "I make decisions about as well as I ever could."))
        self.label_47.setText(_translate("MainWindow", "I put off making decisions more than I used to."))
        self.label_48.setText(_translate("MainWindow", "I have greater difficulty in making decisions more than I used to."))
        self.label_49.setText(_translate("MainWindow", "I can\'t make decisions at all anymore."))
        self.label_50.setText(_translate("MainWindow", "I don\'t feel that I look any worse than I used to."))
        self.label_51.setText(_translate("MainWindow", "I am worried that I am looking old or ugly"))
        self.label_52.setText(_translate("MainWindow", "I feel there are permanent changes in my appearance that make me look ugly"))
        self.label_53.setText(_translate("MainWindow", "I believe I look ugly"))
        self.label_54.setText(_translate("MainWindow", "I can work about as well as before."))
        self.label_55.setText(_translate("MainWindow", "It takes an extra effort to get started at doing something."))
        self.label_56.setText(_translate("MainWindow", "I have to push myself very hard to do anything."))
        self.label_57.setText(_translate("MainWindow", "I can\'t do any work at all."))
        self.label_58.setText(_translate("MainWindow", "I can sleep as well as usual."))
        self.label_59.setText(_translate("MainWindow", "I don\'t sleep as well as I used to."))
        self.label_60.setText(_translate("MainWindow", "I wake up 1-2 hours earlier than usual and find it hard to get back to sleep."))
        self.label_61.setText(_translate("MainWindow", "I wake up several hours earlier than I used to and cannot get back to sleep"))
        self.label_62.setText(_translate("MainWindow", "I don\'t get more tired than usual."))
        self.label_63.setText(_translate("MainWindow", "I get tired more easily than I used to."))
        self.label_64.setText(_translate("MainWindow", "I get tired from doing almost anything."))
        self.label_65.setText(_translate("MainWindow", "I am too tired to do anything."))
        self.label_66.setText(_translate("MainWindow", "My appetite is no worse than usual."))
        self.label_67.setText(_translate("MainWindow", "My appetite is not as good as it used to be."))
        self.label_68.setText(_translate("MainWindow", "My appetite is much worse now."))
        self.label_69.setText(_translate("MainWindow", "I have no appetite at all anymore."))
        self.label_70.setText(_translate("MainWindow", "I\'m no more hungry nor thirsty than I usually am."))
        self.label_71.setText(_translate("MainWindow", "I\'m less hungry or thirsty than usual."))
        self.label_72.setText(_translate("MainWindow", "I have barely eaten anything today."))
        self.label_73.setText(_translate("MainWindow", "I have not eaten anything today."))
        self.label_74.setText(_translate("MainWindow", "I am no more worried about my health than usual."))
        self.label_75.setText(_translate("MainWindow", "I am worried about physical problems like aches, pains etc."))
        self.label_76.setText(_translate("MainWindow", "I am burdened by the thoughts of my poor physical health"))
        self.label_77.setText(_translate("MainWindow", "I cannot concentrate on anything other than my physical ailments."))
        self.label_78.setText(_translate("MainWindow", "I have not noticed any recent change in my interest in sex."))
        self.label_79.setText(_translate("MainWindow", "I am less interested in sex than I used to be."))
        self.label_80.setText(_translate("MainWindow", "I have almost no interest in sex."))
        self.label_81.setText(_translate("MainWindow", "I have lost interest in sex completely."))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">1-10</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> These ups and downs are considered normal </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">11-16</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> Mild mood disturbance </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">17-20</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> Borderline clinical depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">21-30</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> Moderate depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">31-40</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> Severe depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt; font-weight:600;\">over 40</span><span style=\" font-family:\'TimesNewRoman\'; font-size:9pt;\"> Extreme depression </span></p></body></html>"))
        self.sum_box.setSuffix(_translate("MainWindow", " BECKys"))
        self.menuBECK.setTitle(_translate("MainWindow", "BECK"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.actionShowBeckExam.setText(_translate("MainWindow", "Show Input View"))
        self.actionShowBeckExam.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShowBeckTable.setText(_translate("MainWindow", "Show Data View"))
        self.actionShowBeckTable.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete.setText(_translate("MainWindow", "Delete Record(s)"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionNext.setText(_translate("MainWindow", "Next Question"))
        self.actionNext.setShortcut(_translate("MainWindow", "Shift+Num+Right"))
        self.actionPrev.setText(_translate("MainWindow", "Previous Page"))
        self.actionPrev.setShortcut(_translate("MainWindow", "Shift+Num+Left"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionHome.setShortcut(_translate("MainWindow", "Shift+Num+Up"))
